services:
  - type: web
    name: filepass26-backend
    env: node
    plan: free
    root: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
